import { ArrowUp, ArrowUpRight, Mail, MapPin, Phone } from 'lucide-react';
import { Brand, Chapter, Reveal } from './Shared';
import { company, mapsUrl, whatsappUrl } from '../../data/company';

export const WhatsAppIcon = ({ size = 22 }) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M21 11.5a9 9 0 0 1-13.4 7.9L3 21l1.6-4.6A9 9 0 1 1 21 11.5Z"/><path d="M8.5 7.5c-.6 0-1 1-1 1.7 0 2.3 3 5.3 5.3 5.3.7 0 1.7-.4 1.7-1l-1.8-1.2-.8.6a7 7 0 0 1-2.8-2.8l.6-.8Z"/></svg>;

export const Contact = ({ onEnquire }) => <><section id="contact" className="contact-section section-pad" data-testid="contact-section"><div className="page-width"><Chapter number="04" label="LET’S BUILD SOMETHING THAT LASTS." light /><Reveal className="contact-heading"><h2 data-testid="contact-title">GOT A PROJECT?<br /><span className="amber-text">LET’S GET TO WORK.</span></h2><button className="contact-circle" data-testid="contact-project-enquiry" aria-label="Discuss your project" onClick={() => onEnquire()}><ArrowUpRight size={48} strokeWidth={1.2} /></button></Reveal><div className="contact-grid"><div className="contact-people"><span className="eyebrow" data-testid="contact-team-label">YOUR DIRECT LINE TO THE DEPOT</span>{company.contacts.map((contact, i) => <div className="person-contact" data-testid={`contact-person-${i}`} key={contact.number}><div><p>{contact.name}</p><a data-testid={`contact-phone-${i}`} href={`tel:+${contact.number}`}>{contact.phone}</a></div><div className="contact-methods"><a data-testid={`contact-call-${i}`} href={`tel:+${contact.number}`} aria-label={`Call ${contact.name}`}><Phone size={19} /></a><a data-testid={`contact-whatsapp-${i}`} href={whatsappUrl('Hello Mahalaxmi Corporation! I would like to enquire about materials for my project.', i)} target="_blank" rel="noopener noreferrer" aria-label={`WhatsApp ${contact.name}`}><WhatsAppIcon size={21} /></a></div></div>)}</div><div className="depot-location"><span className="eyebrow" data-testid="contact-location-label">COME SAY HELLO</span><h3 data-testid="contact-depot-title"><MapPin size={19} />ANKLESHWAR DEPOT</h3><p data-testid="contact-address">{company.address}</p><a className="underlined-link" data-testid="contact-directions" href={mapsUrl} target="_blank" rel="noopener noreferrer">Get directions <ArrowUpRight size={16} /></a><a className="email-link" data-testid="contact-email" href={`mailto:${company.email}`}><Mail size={15} />{company.email}</a></div></div></div></section>
  <footer className="site-footer" data-testid="site-footer"><div className="page-width"><div className="footer-top"><Brand footer /><p data-testid="footer-company-services">CENTERING & SHUTTERING DEPO. · TIMBER MART<br />ALL TYPES OF MATERIALS FOR RENT & SALE</p><a data-testid="footer-back-to-top" className="back-top" href="#home">BACK TO TOP <ArrowUp size={16} /></a></div><div className="footer-bottom"><span data-testid="footer-copyright">© {new Date().getFullYear()} Mahalaxmi Corporation. All rights reserved.</span><span data-testid="footer-location">BUILT ON TRUST. BASED IN ANKLESHWAR.</span></div></div></footer>
  <a className="floating-whatsapp" data-testid="floating-whatsapp" href={whatsappUrl('Hello Mahalaxmi Corporation! I would like to discuss a rental requirement.')} target="_blank" rel="noopener noreferrer" aria-label="Chat with Mahalaxmi on WhatsApp"><WhatsAppIcon size={26} /><span>Let’s talk</span></a>
</>;