import { ArrowUpRight, Check, Search } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '../ui/dialog';
import { catalogue, company, whatsappUrl } from '../../data/company';
import { WhatsAppIcon } from './Contact';

const EnquiryForm = ({ material }) => {
  const [recipient, setRecipient] = useState('0');
  const submit = e => {
    e.preventDefault();
    const data = new FormData(e.currentTarget);
    const message = `Hello ${company.contacts[Number(recipient)].name}, I would like to enquire with Mahalaxmi Corporation.\n\nName: ${data.get('name').trim()}\nMaterial: ${data.get('material').trim()}\nQuantity: ${data.get('quantity') || 'Please advise'}\nSite: ${data.get('site')?.trim() || 'To be discussed'}\nRequirement: ${data.get('type')}\n\nPlease share availability and a quote. Thank you!`;
    window.open(whatsappUrl(message, Number(recipient)), '_blank', 'noopener,noreferrer');
    toast.info('Continue in WhatsApp', { description: 'Send your prepared message in WhatsApp to complete your enquiry.', duration: 7000 });
  };
  return <><span className="eyebrow dialog-eyebrow" data-testid="enquiry-eyebrow">THE FIRST STEP TO YOUR NEXT BUILD</span><DialogTitle data-testid="enquiry-title" className="dialog-title">LET’S TALK<br /><span className="amber-text">MATERIALS.</span></DialogTitle><DialogDescription data-testid="enquiry-description">Tell us what you need. We’ll prepare a WhatsApp message for the depot — no account needed.</DialogDescription><form onSubmit={submit} className="enquiry-form" data-testid="enquiry-form">
    <label>Your name <span>*</span><input data-testid="enquiry-name" name="name" placeholder="Your full name" required pattern=".*\S.*" maxLength={100} autoComplete="name" /></label>
    <label>Material <span>*</span><input data-testid="enquiry-material" name="material" placeholder="e.g. Shuttering plates, 3 × 2" defaultValue={material} required pattern=".*\S.*" maxLength={200} /></label>
    <div className="form-row"><label>Quantity<input data-testid="enquiry-quantity" name="quantity" type="number" min="1" step="1" placeholder="Number of units" /></label><label>I’m looking to<select name="type" data-testid="enquiry-type"><option>Rent</option><option>Buy</option><option>Discuss options</option></select></label></div>
    <label>Project / site location<input data-testid="enquiry-site" name="site" placeholder="Your project location" maxLength={250} /></label>
    <label>Speak with<select value={recipient} onChange={e => setRecipient(e.target.value)} data-testid="enquiry-recipient">{company.contacts.map((contact, i) => <option key={contact.number} value={i}>{contact.name} · {contact.phone}</option>)}</select></label>
    <button className="action whatsapp-submit" type="submit" data-testid="enquiry-submit"><WhatsAppIcon size={20} />Continue on WhatsApp<ArrowUpRight size={19} /></button><p className="form-disclaimer" data-testid="enquiry-disclaimer">Opens WhatsApp with your message. Rates, stock, transport and rental terms are confirmed directly by our team.</p>
  </form></>;
};

const CatalogueView = ({ onEnquire }) => {
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('All');
  const items = catalogue.filter(item => (category === 'All' || item[2] === category) && `${item[0]} ${item[1]} ${item[2]}`.toLowerCase().includes(search.toLowerCase().trim()));
  return <><span className="eyebrow dialog-eyebrow" data-testid="catalogue-eyebrow">THE MATERIAL DIRECTORY</span><DialogTitle className="dialog-title" data-testid="catalogue-title">YOUR BUILD.<br /><span className="amber-text">OUR RANGE.</span></DialogTitle><DialogDescription data-testid="catalogue-description">23 listed materials and sizes from our depot catalogue. Looking for scaffolding or something else? Ask our team.</DialogDescription><div className="catalogue-tools"><label className="catalogue-search"><Search size={18} /><input data-testid="catalogue-search" aria-label="Search catalogue" placeholder="Search by material, size or code…" value={search} onChange={e => setSearch(e.target.value)} /></label><select data-testid="catalogue-category" aria-label="Filter catalogue category" value={category} onChange={e => setCategory(e.target.value)}>{['All', 'Shuttering', 'Props & jacks', 'Timber & ply', 'Accessories'].map(c => <option key={c} value={c}>{c === 'All' ? 'All categories' : c}</option>)}</select></div><div className="catalogue-count mono" data-testid="catalogue-result-count">{items.length} MATERIAL{items.length !== 1 ? 'S' : ''} FOUND</div><div className="catalogue-table-wrap"><table className="catalogue-table" data-testid="catalogue-table"><thead><tr><th>Material / size</th><th>Ref. daily rate</th><th>Service / unit</th><th><span className="sr-only">Enquire</span></th></tr></thead><tbody>{items.map(([id, name, cat, rate, service]) => <tr data-testid={`catalogue-row-${id}`} key={id}><td><span className="mono catalogue-code">{id}</span><strong>{name}</strong><small>{cat}</small></td><td>{rate === null ? 'Ask us' : `₹${rate.toFixed(2)}`}</td><td>{service === null ? 'Ask us' : `₹${service.toFixed(2)}`}</td><td><button data-testid={`catalogue-enquire-${id}`} onClick={() => onEnquire(name)} aria-label={`Enquire about ${name}`}><ArrowUpRight size={20} /></button></td></tr>)}</tbody></table>{items.length === 0 && <div className="catalogue-empty" data-testid="catalogue-empty"><p>No materials match your search.</p><button data-testid="catalogue-clear-filters" className="underlined-link" onClick={() => { setSearch(''); setCategory('All'); }}>Clear filters <ArrowUpRight size={16} /></button></div>}</div><p className="catalogue-note" data-testid="catalogue-rate-note">Reference rates from the supplied catalogue, not a live quotation. Rates, taxes, service charges and availability must be confirmed with the depot. Running-feet items are billed by applicable length; size labels retain the depot’s notation.</p><button className="action" data-testid="catalogue-custom-enquiry" onClick={() => onEnquire()}>Ask about another material <ArrowUpRight size={18} /></button></>;
};

const ProductView = ({ product, onEnquire }) => <><div className="detail-image"><img src={product.image} className={product.imageClass} alt={product.name} /><span className="mono">MATERIAL / {product.number}</span></div><span className="eyebrow dialog-eyebrow" data-testid="product-detail-category">{product.category}</span><DialogTitle data-testid="product-detail-title" className="product-dialog-title">{product.name}</DialogTitle><DialogDescription data-testid="product-detail-description">{product.description}</DialogDescription><div className="product-applications" data-testid="product-applications">{product.uses.map(use => <span key={use}><Check size={14} />{use}</span>)}</div><div className="product-specification" data-testid="product-specification"><span className="eyebrow">SIZES & CONFIGURATIONS</span><p>{product.sizes}</p></div><button className="action" data-testid="product-detail-enquire" onClick={() => onEnquire(product.name)}>Enquire about this material <ArrowUpRight size={18} /></button><p className="form-disclaimer" data-testid="product-availability-note">Availability and rental terms confirmed on enquiry.</p></>;

export const RentalDialogs = ({ dialog, setDialog, material, product, onEnquire }) => <Dialog open={Boolean(dialog)} onOpenChange={open => { if (!open) setDialog(null); }}><DialogContent data-lenis-prevent className={`rental-dialog ${dialog === 'catalogue' ? 'catalogue-dialog' : ''}`} data-testid="rental-dialog">{dialog === 'enquiry' && <EnquiryForm material={material} />}{dialog === 'catalogue' && <CatalogueView onEnquire={onEnquire} />}{dialog === 'product' && product && <ProductView product={product} onEnquire={onEnquire} />}</DialogContent></Dialog>;